ApiVersion: 0.0.1
Env: dev
Namespace: xxx.cluster
application:
  Listen:
      http: :8088
      grpc: :9099
  Registry:
      etcdv3:
        endpoints: ["127.0.0.1:2379"]
        dialTimeout: 10s
Service:
  Name: ordersvc
  Redis:
    Addr: 127.0.0.1
    Port: :6377
  
